# Resnet Mutate

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
from torchinfo import summary
from tqdm import tqdm
import matplotlib.pyplot as plt

from local import model
from local import imagenet
from local import resnet
from local.device import device, cpu


print("PyTorch Version: ", torch.__version__)
print("Torchvision Version: ", torchvision.__version__)
print("Pytorch device: ", device)


/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: <BE0CCD9A-269A-30E2-A23C-DA45E89EBB1F> /Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so
  Reason: tried: '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/lib-dynload/../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/bin/../lib/libjpeg.8.dylib' (no such file), '/System/Vol

PyTorch Version:  1.13.1
Torchvision Version:  0.14.1a0
Pytorch device:  mps


In [2]:
train_data = imagenet.train_data("data/imagenet-1k/train/")

In [9]:
resnet18 = resnet.resnet18()
model.reset(resnet18)

In [10]:
resnet18.get_parameter('conv1.weight')[0, 0]

tensor([[-0.0150,  0.0642,  0.0674,  0.0111, -0.0180, -0.0245,  0.0424],
        [-0.0693, -0.0623, -0.0239, -0.0376,  0.0013,  0.0070,  0.0778],
        [ 0.0795,  0.0551, -0.0144,  0.0444, -0.0258,  0.0435, -0.0149],
        [-0.0216, -0.0495, -0.0425, -0.0182,  0.0074, -0.0238,  0.0343],
        [ 0.0398, -0.0557,  0.0132, -0.0121, -0.0366,  0.0563, -0.0399],
        [-0.0733, -0.0225,  0.0700, -0.0769, -0.0795,  0.0618, -0.0789],
        [-0.0790, -0.0557, -0.0770,  0.0247,  0.0277, -0.0352,  0.0248]],
       grad_fn=<SelectBackward0>)

In [5]:
with torch.no_grad():
    resnet18.get_parameter('conv1.weight')[0, 0, 0, 0].copy_(7)

In [12]:
resnet18.get_parameter('conv1.weight')[0, 0]

tensor([[ 7.0000e+00, -3.1703e-02,  2.4431e-02,  2.5522e-02,  2.4349e-03,
          5.8660e-02, -7.6692e-02],
        [ 3.1217e-02, -7.9921e-02,  5.3224e-02,  2.6282e-02,  5.6118e-02,
         -1.5078e-02,  2.1643e-02],
        [ 4.0474e-02, -6.4064e-02,  7.6471e-02,  1.0004e-02, -7.1027e-02,
         -4.9162e-02,  7.5553e-03],
        [ 6.1721e-02, -5.7884e-02,  6.4272e-02,  5.2553e-03,  6.9369e-02,
         -4.5745e-02,  2.4190e-02],
        [-1.9684e-02,  1.9963e-02,  2.8986e-02,  2.2048e-02,  1.7536e-02,
         -5.9144e-02, -5.8423e-02],
        [-4.2318e-02,  7.9948e-02, -3.9535e-02,  1.2453e-02, -5.1993e-02,
          5.4344e-02, -1.9071e-02],
        [-4.1960e-02,  5.0471e-02, -4.5170e-02,  4.7843e-02,  5.5428e-02,
          4.1645e-02, -4.9374e-02]], device='mps:0', grad_fn=<SelectBackward0>)

In [11]:
imagenet.train(resnet18, "resnet18-weird", train_data)

Loading `models/resnet18-weird.00000000.pkl`
Loading `models/resnet18-weird.__optim__.00000000.pkl`
Resuming from epoch 0
Iterating 1281167 samples


  0%|          | 0/5005 [00:00<?, ?it/s]/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: <BE0CCD9A-269A-30E2-A23C-DA45E89EBB1F> /Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so
  Reason: tried: '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/lib-dynload/../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/bin/../lib/libjp

KeyboardInterrupt: 

In [8]:
resnet18.get_parameter('conv1.weight')[0, 0]

/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torch/_tensor_str.py:115: UserWarning: The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/miniforge3/conda-bld/pytorch-recipe_1675740407425/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(


tensor([[ 7.0028e+00, -3.3065e-02,  2.2718e-02,  2.7749e-02,  5.0669e-03,
          6.1308e-02, -7.3644e-02],
        [ 3.3799e-02, -7.7425e-02,  5.5414e-02,  2.8869e-02,  5.8178e-02,
         -1.2753e-02,  2.4034e-02],
        [ 4.2258e-02, -6.1933e-02,  7.7844e-02,  1.1962e-02, -6.9836e-02,
         -4.7697e-02,  9.2275e-03],
        [ 6.2999e-02, -5.6523e-02,  6.4538e-02,  6.5080e-03,  7.0386e-02,
         -4.3921e-02,  2.6447e-02],
        [-2.0440e-02,  1.8512e-02,  2.8877e-02,  2.2935e-02,  1.8900e-02,
         -5.6976e-02, -5.5925e-02],
        [-4.6492e-02,  7.5388e-02, -3.9955e-02,  1.3111e-02, -5.1436e-02,
          5.6286e-02, -1.6731e-02],
        [-4.6559e-02,  4.5855e-02, -4.7200e-02,  4.8481e-02,  5.6181e-02,
          4.3506e-02, -4.7350e-02]], device='mps:0', grad_fn=<SelectBackward0>)

In [13]:
model.clean("resnet18-weird")

Deleting `models/resnet18-weird.00000000.pkl`
Deleting `models/resnet18-weird.__optim__.00000000.pkl`
