# Resnet Inflate

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
from torchinfo import summary
from tqdm import tqdm
import matplotlib.pyplot as plt

from local import data
from local import resnet
from local import train
from local.device import device, cpu


print("PyTorch Version: ", torch.__version__)
print("Torchvision Version: ", torchvision.__version__)
print("Pytorch device: ", device())


PyTorch Version:  1.13.1
Torchvision Version:  0.14.1a0
Device: mps
Pytorch device:  mps


In [3]:
train_data = data.load_dataset("data/imagenet-1k/train/", transform=data.train_transform())
train_loader = torch.utils.data.DataLoader2(
    train_data,
    batch_size=8,
    shuffle=True,
    collate_fn=data.train_collate_fn(train_data)
)

Loading data `data/imagenet-1k/train/`... DONE


In [9]:
_, resnet50_epoch0, epoch, _ = resnet.network_load("remotes/europe-west4-a/tpu-eu-5/resnet50", reset=True, epoch=0)
epoch

Loading `remotes/europe-west4-a/tpu-eu-5/resnet50/00000000.pkl`... DONE


0

In [11]:
_, resnet50_epoch1, epoch, _ = resnet.network_load("remotes/europe-west4-a/tpu-eu-5/resnet50", reset=True, epoch=1)
epoch

Loading `remotes/europe-west4-a/tpu-eu-5/resnet50/00000001.pkl`... DONE


1

In [14]:
_, resnet50_epoch100, epoch, _ = resnet.network_load("remotes/europe-west4-a/tpu-eu-5/resnet50", reset=True, epoch=100)
epoch

Loading `remotes/europe-west4-a/tpu-eu-5/resnet50/00000100.pkl`... DONE


100

In [23]:
_, resnet50_epoch400, epoch, _ = resnet.network_load("remotes/europe-west4-a/tpu-eu-5/resnet50", reset=True, epoch=400)
epoch

Loading `remotes/europe-west4-a/tpu-eu-5/resnet50/00000400.pkl`... DONE


400

In [17]:
[x for x,_ in resnet50_epoch100.named_parameters()]

['conv1.weight',
 'bn1.weight',
 'bn1.bias',
 'layer1.0.conv1.weight',
 'layer1.0.bn1.weight',
 'layer1.0.bn1.bias',
 'layer1.0.conv2.weight',
 'layer1.0.bn2.weight',
 'layer1.0.bn2.bias',
 'layer1.0.conv3.weight',
 'layer1.0.bn3.weight',
 'layer1.0.bn3.bias',
 'layer1.0.downsample.0.weight',
 'layer1.0.downsample.1.weight',
 'layer1.0.downsample.1.bias',
 'layer1.1.conv1.weight',
 'layer1.1.bn1.weight',
 'layer1.1.bn1.bias',
 'layer1.1.conv2.weight',
 'layer1.1.bn2.weight',
 'layer1.1.bn2.bias',
 'layer1.1.conv3.weight',
 'layer1.1.bn3.weight',
 'layer1.1.bn3.bias',
 'layer1.2.conv1.weight',
 'layer1.2.bn1.weight',
 'layer1.2.bn1.bias',
 'layer1.2.conv2.weight',
 'layer1.2.bn2.weight',
 'layer1.2.bn2.bias',
 'layer1.2.conv3.weight',
 'layer1.2.bn3.weight',
 'layer1.2.bn3.bias',
 'layer2.0.conv1.weight',
 'layer2.0.bn1.weight',
 'layer2.0.bn1.bias',
 'layer2.0.conv2.weight',
 'layer2.0.bn2.weight',
 'layer2.0.bn2.bias',
 'layer2.0.conv3.weight',
 'layer2.0.bn3.weight',
 'layer2.0.bn3.b

In [19]:
resnet50_epoch0.get_parameter('fc.weight')[0]

tensor([-0.0077, -0.0068, -0.0108,  ...,  0.0076,  0.0019, -0.0113],
       grad_fn=<SelectBackward0>)

In [20]:
resnet50_epoch1.get_parameter('fc.weight')[0]

tensor([-0.0077, -0.0068, -0.0108,  ...,  0.0076,  0.0019, -0.0113],
       grad_fn=<SelectBackward0>)

In [ ]:
resnet50_epoch100.get_parameter('fc.weight')[0]

tensor([-0.0077, -0.0068, -0.0108,  ...,  0.0076,  0.0019, -0.0113],
       grad_fn=<SelectBackward0>)

In [24]:
resnet50_epoch400.get_parameter('fc.weight')[0]

tensor([-0.0077, -0.0068, -0.0108,  ...,  0.0076,  0.0019, -0.0113],
       grad_fn=<SelectBackward0>)