# Resnet Inflate

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
from torchinfo import summary
from tqdm import tqdm
import matplotlib.pyplot as plt

from local import model
from local import imagenet
from local import resnet
from local.device import device, cpu


print("PyTorch Version: ", torch.__version__)
print("Torchvision Version: ", torchvision.__version__)
print("Pytorch device: ", device)


/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: <BE0CCD9A-269A-30E2-A23C-DA45E89EBB1F> /Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so
  Reason: tried: '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/lib-dynload/../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/bin/../lib/libjpeg.8.dylib' (no such file), '/System/Vol

PyTorch Version:  1.13.1
Torchvision Version:  0.14.1a0
Pytorch device:  mps


In [2]:
# training_data = torchvision.datasets.ImageNet('~/Documents/research/imagenet/', split="train", transform=preprocess)
data_root = '~/Documents/research/imagenet/ILSVRC/Data/CLS-LOC/train/'

train_data = imagenet.train_data(data_root)
eval_data = imagenet.eval_data(data_root)

In [18]:
resnet18 = model.clone(resnet.resnet18)
model.reset(resnet18)

In [19]:
resnet18.get_parameter('conv1.weight')[0, 0]

tensor([[ 0.0353,  0.0084,  0.0771,  0.0231, -0.0063,  0.0545,  0.0816],
        [ 0.0307, -0.0671, -0.0247,  0.0243, -0.0538, -0.0601, -0.0325],
        [-0.0780,  0.0163, -0.0806,  0.0589, -0.0789,  0.0383,  0.0328],
        [-0.0500,  0.0226,  0.0102,  0.0103,  0.0759,  0.0591,  0.0013],
        [ 0.0508, -0.0738, -0.0698,  0.0198,  0.0481,  0.0292,  0.0657],
        [ 0.0419,  0.0394, -0.0205,  0.0610,  0.0715,  0.0286,  0.0213],
        [-0.0002, -0.0051,  0.0125,  0.0691, -0.0030,  0.0765, -0.0234]],
       grad_fn=<SelectBackward0>)

In [5]:
with torch.no_grad():
    resnet18.get_parameter('conv1.weight')[0, 0, 0, 0].copy_(7)

In [6]:
resnet18.get_parameter('conv1.weight')[0, 0]

tensor([[ 7.0000e+00, -7.8849e-02, -3.3931e-02,  5.2948e-02, -4.9853e-02,
          5.6393e-03,  7.6273e-02],
        [-6.7875e-02, -5.4992e-02,  3.5354e-02, -4.9503e-02,  9.0973e-04,
          4.5436e-02, -4.2899e-02],
        [-6.7054e-02,  1.2798e-02, -4.5688e-02,  7.7972e-02,  6.7924e-02,
          3.8875e-02, -4.6609e-02],
        [ 4.0996e-02,  4.1386e-02, -2.8161e-02, -2.8988e-02,  3.4288e-02,
         -1.2576e-02,  3.4341e-02],
        [ 6.9747e-02,  4.1352e-02, -5.2760e-02, -7.1929e-02,  4.4207e-02,
         -4.7194e-02, -7.6278e-02],
        [ 6.1800e-02,  2.5360e-02,  4.3323e-03,  2.5244e-02, -3.2290e-02,
          2.0035e-02, -8.1175e-02],
        [ 5.5473e-02,  5.9598e-02,  5.2584e-02,  2.6949e-02, -7.0485e-02,
         -3.1272e-03, -5.3211e-02]], grad_fn=<SelectBackward0>)

In [20]:
imagenet.train(resnet18, "resnet18-weird", train_data)

Loading `models/resnet18-weird.00000000.pkl`
Loading `models/resnet18-weird.__optim__.00000000.pkl`
Resuming from epoch: 0


  0%|          | 0/5005 [00:00<?, ?it/s]/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: <BE0CCD9A-269A-30E2-A23C-DA45E89EBB1F> /Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/image.so
  Reason: tried: '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/site-packages/torchvision/../../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/lib/python3.10/lib-dynload/../../libjpeg.8.dylib' (no such file), '/Users/marakim/opt/anaconda3/envs/network_inflation/bin/../lib/libjp

KeyboardInterrupt: 

In [21]:
resnet18.get_parameter('conv1.weight')[0, 0]

tensor([[ 6.9837e+00, -3.2412e-02,  3.4744e-02,  1.0496e-02,  2.3584e-02,
          6.3414e-03,  8.1645e-03],
        [-1.7233e-02,  1.8373e-04,  1.3185e-02, -2.0498e-02, -7.9313e-02,
          6.7966e-02,  3.5911e-02],
        [ 5.9609e-02,  1.6616e-02, -1.2924e-02, -1.7000e-02, -5.5093e-02,
         -3.1406e-02,  2.6216e-02],
        [ 5.3423e-02,  8.4579e-03, -3.9318e-02,  5.2294e-02,  4.0801e-02,
         -3.0285e-02,  5.6518e-02],
        [ 7.4207e-02, -1.4734e-03, -3.7540e-02, -4.6742e-02,  6.4366e-02,
          7.3403e-02,  4.9157e-02],
        [ 2.1152e-02,  7.6027e-02,  8.0330e-02,  6.5794e-02,  8.3597e-03,
          2.0843e-02, -1.3538e-02],
        [ 6.5672e-02,  5.8462e-02, -2.3950e-02, -5.0412e-02, -3.8521e-02,
          5.0084e-02, -6.3036e-03]], device='mps:0', grad_fn=<SelectBackward0>)